### ISSUE TITLE
GLIB.FileError

### ISSUE THREAD

**Issue by htcosta** [mheine/gnome-shell-spotify-label#8]
GLib.FileError: Failed to open file “/home/user/.local/share/gnome-shell/extensions/gnomespotifylabel@mheine.github.com/schemas/gschemas.compiled”: open() failed: No such file or directory

Stack trace:
  buildPrefsWidget@/home/user/.local/share/gnome-shell/extensions/gnomespotifylabel@mheine.github.com/prefs.js:15:44
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by raujonas** [comment]
@htcosta please try to create a folder called "schemas" inside the extension folder at "home/user/.local/share/gnome-shell/extensions/gnomespotifylabel@mheine.github.com/". 

Then move the file "gschemas.compiled" and "org.gnome.shell.extensions.spotifylabel.gschema.xml" into the new folder. It should look like this then:
![grafik](https://user-images.githubusercontent.com/25148277/97149274-d0af7a80-176c-11eb-8a61-72bff7cf1045.png)

If you are on Ubuntu you can restart your gnome shell with "Alt + F2" and "r" afterwards.

@mheine it seems that these two files are in the root of the new zip folder instead of the schemas/ folder. It works locally if I use `zip -r gnomespotifylabel@mheine.github.com schemas/ extension.js metadata.json prefs.js stylesheet.css`

**Comment by htcosta** [comment]
That worked, was on Fedora 32, Gnome 3.36.6

**Comment by mheine** [comment]
@raujonas I'm fairly sure that I've always used the `-r` flag and included `schemas/`, but I'm not certain. I probably have the command stored in my history on my local machine, so I'll have a look at this as soon as I can :slightly_smiling_face:

**Comment by M1ke** [comment]
https://github.com/mheine/gnome-shell-spotify-label/issues/8#issuecomment-716394666

This also works on Ubuntu 20.04

**Comment by krushndayshmookh** [comment]
> @htcosta please try to create a folder called "schemas" inside the extension folder at "home/user/.local/share/gnome-shell/extensions/gnomespotifylabel@mheine.github.com/".
> 
> Then move the file "gschemas.compiled" and "org.gnome.shell.extensions.spotifylabel.gschema.xml" into the new folder. It should look like this then:
> ![grafik](https://user-images.githubusercontent.com/25148277/97149274-d0af7a80-176c-11eb-8a61-72bff7cf1045.png)
> 
> If you are on Ubuntu you can restart your gnome shell with "Alt + F2" and "r" afterwards.
> 
> @mheine it seems that these two files are in the root of the new zip folder instead of the schemas/ folder. It works locally if I use `zip -r gnomespotifylabel@mheine.github.com schemas/ extension.js metadata.json prefs.js stylesheet.css`

thanks

**Comment by rrileyca** [comment]
raujonas fix worked for me, Ubuntu 20.10
